services:
  proxy:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      STAGE: local
      DOMAINS: |
        crud.localtest.me -> http://app:3000
        crud2.localtest.me -> http://app2:3000
      ERROR_LOG: /var/log/nginx/error.log
      ACCESS_LOG: /var/log/nginx/access.log
      WEBSOCKET: "true"
    volumes: 
      - ./proxy/certs:/var/lib/https-portal
      - ./proxy/conf:/etc/nginx/conf.d
      - ./proxy/nginx-conf/crud.localtest.me.ssl.conf.erb:/var/lib/nginx-conf/crud.localtest.me.ssl.conf.erb:ro
      - ./proxy/nginx-conf/crud2.localtest.me.ssl.conf.erb:/var/lib/nginx-conf/crud2.localtest.me.ssl.conf.erb:ro
      - ./proxy/log:/var/log/nginx/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace/html:/var/www/html
    tty: true
    stdin_open: true

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace/html:/var/www/html
    tty: true
    stdin_open: true

  db_mysql:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql

  db_postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql:/var/lib/postgresql
