services:
  proxy:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      STAGE: local
      DOMAINS: |
        n2.localhost -> http://app
      ERROR_LOG: /var/log/nginx/error.log
      ACCESS_LOG: /var/log/nginx/access.log
      WEBSOCKET: "true"
    volumes: 
      - ./proxy/certs:/var/lib/https-portal
      - ./proxy/conf:/etc/nginx/conf.d
      - ./proxy/nginx-conf/n2.localhost.ssl.conf.erb:/var/lib/nginx-conf/n2.localhost.ssl.conf.erb:ro
      - ./proxy/log:/var/log/nginx/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    tty: true
    stdin_open: true
